version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: tasksapi-postgres
    environment:
      POSTGRES_DB: tasksdb
      POSTGRES_USER: tasksuser
      POSTGRES_PASSWORD: taskspass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tasksapi-network

  # Spring Boot Application
  app:
    build: .
    container_name: tasksapi-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tasksdb
      SPRING_DATASOURCE_USERNAME: tasksuser
      SPRING_DATASOURCE_PASSWORD: taskspass
      APP_JWT_SECRET: mySecretKey123456789012345678901234567890
      APP_JWT_EXPIRATION_MS: 86400000
    depends_on:
      - postgres
    networks:
      - tasksapi-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  tasksapi-network:
    driver: bridge 